.PHONY: clean All

All:
	@echo "----------Building project:[ VCODE - Debug ]----------"
	@cd "H:\Dev\VCODE\VCODE" && $(MAKE) -f  "VCODE.mk"
clean:
	@echo "----------Cleaning project:[ VCODE - Debug ]----------"
	@cd "H:\Dev\VCODE\VCODE" && $(MAKE) -f  "VCODE.mk" clean
