.PHONY: clean All

All:
	@echo "----------Building project:[ IndieBoy - Debug ]----------"
	@$(MAKE) -f  "IndieBoy.mk"
clean:
	@echo "----------Cleaning project:[ IndieBoy - Debug ]----------"
	@$(MAKE) -f  "IndieBoy.mk" clean
